### ISSUE TITLE
Move left righ with arrow keys

### ISSUE THREAD

**Issue by rayman3003** [VPKSoft/amp-multi#194]
Could u please add the possibility to move the song 5seconds to left or right, by the arrow keys of keyboard?

**Comment by VPKSoft** [comment]
Sure - shouldn't be too difficult 👍

**Comment by rayman3003** [comment]
> Sure - shouldn't be too difficult 👍

Thank u. 🙏

**Comment by VPKSoft** [comment]
Hi,
Thanks for the enhancement suggestion 👍, the new version: https://github.com/VPKSoft/amp-multi/releases/tag/v.1.0.5

**Comment by rayman3003** [comment]
Awesome 😍

One more thing: If it's possible please put a 7z compressed release for windows version too. With 7z compression, the size of the app will be reduced dramatically; & saves time & space.
